---
- hosts: web-servers
  become: true
  
  tasks:
    - name: copy war file onto docker host
      copy: 
      src: /var/lib/jenkins/workspace/ansible-docker/target/petclinic.war
      dest: /opt/docker
