---
- hosts: web-servers
  become: true
  
  tasks:
    - name: create docker image using war file
      command: docker build -t petclinic:latest .

    - name: create tag to image
      command: docker tag petclinic nareshbabu1991/petclinic

    - name: push image on to dockerhub
      command: docker push nareshbabu1991/petclinic


    - name: remove docker images from ansible server
      command: docker rmi petclinic:latest nareshbabu1991/petclinic
      ignore_errors: yes
