---
- name: Deploy petclinic.war to Docker host
  hosts: webservers
  become: true

  tasks:
    - name: copy war file form ansible server to docker host
      copy:
        src: /target/petclinic.war
        dest: /opt/artifact/petclinic.jar
